# Tensor

- Simple Tensor

In [1]:
a = [1.0, 2.0, 1.0]

In [2]:
a[2]

1.0

- Change Tensor

In [3]:
a[2] = 3.0
a

[1.0, 2.0, 3.0]

- Create three Tensor

In [4]:
import torch # <1>
a = torch.ones(3) # <2>
a

tensor([1., 1., 1.])

- Show a[0]

In [5]:
a[0]

tensor(1.)

- Use float format

In [6]:
float(a[1])

1.0

- Change a[2]

In [7]:
a[2] = 2.0
a

tensor([1., 1., 2.])

- Create six zero Tensors

In [8]:
points = torch.zeros(6) # <1>
points[0] = 4.0 # <2>
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

- Give nums for Tensor

In [9]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

- Use float format

In [10]:
float(points[0]), float(points[1])

(4.0, 1.0)

- 2 dimensional

In [11]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

- Print shape

In [12]:
points.shape

torch.Size([3, 2])

- Create 3x2 zero Tensor

In [13]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

- Give nums to Tensor

In [14]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

- Show [0,1]

In [15]:
points[0, 1]

tensor(1.)

- Show row[0]

In [16]:
points[0]

tensor([4., 1.])